// AUTO-GENERATED by scripts/sync-products.mjs
// Do not edit manually. Edit product-files/<slug>/product.json and run the sync script.

export type ProductDefinition = {
  slug: string;
  code: string;
  name: string;
  priceId: string;
  priceText: string;
  version: string;
  fileName: string;
  pagePath: string;
  description: string;
  descriptionEn: string;
  highlights: readonly string[];
  enabled: boolean;
  bytes: number;
  sha256: string;
};

export const PRODUCTS = [
  {
    "slug": "pm01",
    "code": "PM-01",
    "name": "PM-01 Production Order Management Professional Edition",
    "priceId": "pri_01m0qa28dxwsgfbgcq3b0b78hq",
    "priceText": "US$9.90",
    "version": "V1.0",
    "fileName": "BaiheAI_PM01_Production_Order_Management_Pro_V1_0.zip",
    "pagePath": "/product/pm01",
    "description": "带 VBA 宏的 Excel 生产订单管理系统，用于客户/商品/员工资料、订单与生产录入、订单进度、产量统计、查询和进度看板。",
    "descriptionEn": "Pre-built macro-enabled Excel production order management software for master data, order entry, production entry, progress tracking, output statistics, queries and dashboards.",
    "highlights": [
      "客户 / 商品 / 员工基础资料",
      "订单录入与生产录入",
      "订单进度与产量统计",
      "订单查询与进度看板",
      "VBA 宏与窗体操作",
      "Windows / Microsoft Excel 桌面版"
    ],
    "enabled": true,
    "bytes": 1051397,
    "sha256": "890b46bd3e8a4fdddc50d61c5744838a9a9263a3b2dbf833372f216a9a980a5e"
  },
  {
    "slug": "qc01",
    "code": "QC-01",
    "name": "QC-01 Professional Edition",
    "priceId": "pri_01m0mwe8b43bh9an0b6vj40m27",
    "priceText": "US$9.90",
    "version": "V2.1",
    "fileName": "BaiheAI_QC01_Pro_V2_1.zip",
    "pagePath": "/inspection-record/pro",
    "description": "面向工厂长期质量记录、AQL抽样、查询、打印与追溯的本地专业工具。",
    "descriptionEn": "Pre-built factory quality inspection software for long-term records, AQL sampling, traceability, queries and printable reports.",
    "highlights": [
      "进料 / 过程 / 成品检验长期记录",
      "AQL 自动判定",
      "历史查询与质量看板",
      "简版 / 完整版打印",
      "Windows / Microsoft Excel 本地使用"
    ],
    "enabled": true,
    "bytes": 80307,
    "sha256": "e35611039d5376a07e181a07b6522d69acfb53826a21f5716439bee00a7c77f4"
  }
] as const satisfies readonly ProductDefinition[];

export function getProductBySlug(slug: string) {
  return PRODUCTS.find((product) => product.slug === slug);
}

export function getProductByPriceId(priceId: string) {
  return PRODUCTS.find((product) => product.priceId === priceId);
}
